export default {
  grid: {
    container: '111rem',
  },
  border: {
    small: '0.8rem',
    large: '3.2rem',
  },
  colors: {
    primary: '#5A42D2',
    accent: '#916FFF',
    highContrast: '#FFFFFF',
    lowContrast: '#A3A2A6',
    background: '#181621',
    backgroundElevateOne: '#211F2A',
    backgroundElevateTwo: '#26242E',
    backgroundElevateThree: '#2D2B35',
    backgroundElevateFour: '#383740',
    backgroundDefault: '#D9E6F6',
    backgroundPrimary: '#d9e6f6',
    backgroundSecondary: '#F1F9FE',
    backgroundTertiary: '#ffffff',
    backgroundQuarternary: '#bbcde8',
    backgroundQuinary: '#308bc5',
    colorPrimary: '#2E7BB4',
    colorSecondary: '#388BB0',
    colorTertiary: '#2F4A71',
    colorQuarternary: '#d81d99',
    textPrimaryColor: '#333333',
    textSecondaryColor: '#ffffff',
    textTertiaryColor: '#5a5a5a',
    textQuarternaryColor: '#c5c6ca',
  },
  font: {
    family:
      "Rubik, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    normal: 400,
    bold: 800,
    sizes: {
      xsmall: '1.2rem',
      small: '1.4rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.0rem',
      xxlarge: '2.8rem',
      huge: '5.2rem',
    },
  },
  spacings: {
    xxsmall: '0.8rem',
    xsmall: '1rem',
    small: '1.2rem',
    medium: '1.4rem',
    large: '1.6rem',
    xlarge: '2rem',
    xxlarge: '2.4rem',
  },
};
